version: '3.8'

services:
  main-db:
    image: mysql:latest
    restart: always
    container_name: main-db
    environment:
      MYSQL_DATABASE: 'crud'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - '3307:3306'
    volumes: 
      - ./data/db:/var/lib/mysql
